In [1]:
import glob
import numpy as np
from PIL import Image
import pandas as pd
import os
import matplotlib.pyplot as plt
from tqdm import tqdm

In [3]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [7]:
df = pd.read_csv('ML_ALL.csv')

In [9]:
df

Unnamed: 0    pixel1    pixel2    pixel3    pixel4    pixel5    pixel6  \
0            311  0.003922  0.003922  0.000000  0.635294  0.007843  0.011765   
1            950  0.647059  0.639216  0.698039  0.654902  0.654902  0.674510   
2            594  0.003922  0.003922  0.000000  0.000000  0.003922  0.007843   
3            258  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
4           3128  0.003922  0.000000  0.007843  0.007843  0.007843  0.007843   
...          ...       ...       ...       ...       ...       ...       ...   
3251          58  0.000000  0.011765  0.000000  0.000000  0.000000  0.000000   
3252        2162  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
3253        1204  0.019608  0.027451  0.101961  0.450980  0.031373  0.011765   
3254        1800  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
3255         485  0.035294  0.011765  0.015686  0.011765  0.003922  0.007843   

        pixel7    pixel8    pixel9  ...  pixel50171  pixel50172  pixel50173  \
0     0.701961  0.698039  0.737255  ...    0.023529    0.011765    0.003922   
1     0.654902  0.576471  0.588235  ...    0.000000    0.000000    0.000000   
2     0.003922  0.007843  0.007843  ...    0.000000    0.000000    0.000000   
3     0.000000  0.000000  0.000000  ...    0.000000    0.003922    0.003922   
4     0.007843  0.003922  0.000000  ...    0.015686    0.019608    0.023529   
...        ...       ...       ...  ...         ...         ...         ...   
3251  0.000000  0.003922  0.000000  ...    0.000000    0.000000    0.000000   
3252  0.000000  0.000000  0.000000  ...    0.007843    0.003922    0.007843   
3253  0.003922  0.007843  0.003922  ...    0.000000    0.000000    0.003922   
3254  0.000000  0.000000  0.000000  ...    0.000000    0.000000    0.000000   
3255  0.003922  0.003922  0.000000  ...    0.000000    0.000000    0.000000   

      pixel50174  pixel50175  pixel50176  Benign  Early  Pre  Pro  
0       0.003922    0.011765    0.007843     1.0    0.0  0.0  0.0  
1       0.000000    0.000000    0.000000     0.0    1.0  0.0  0.0  
2       0.000000    0.000000    0.000000     0.0    1.0  0.0  0.0  
3       0.007843    0.011765    0.643137     1.0    0.0  0.0  0.0  
4       0.015686    0.003922    0.011765     0.0    0.0  0.0  1.0  
...          ...         ...         ...     ...    ...  ...  ...  
3251    0.000000    0.000000    0.000000     1.0    0.0  0.0  0.0  
3252    0.003922    0.019608    0.027451     0.0    0.0  1.0  0.0  
3253    0.003922    0.000000    0.003922     0.0    1.0  0.0  0.0  
3254    0.000000    0.000000    0.000000     0.0    0.0  1.0  0.0  
3255    0.000000    0.000000    0.000000     1.0    0.0  0.0  0.0  

[3256 rows x 50181 columns]

In [13]:
df = df.drop('Unnamed: 0', axis=1)

In [15]:
df

pixel1    pixel2    pixel3    pixel4    pixel5    pixel6    pixel7  \
0     0.003922  0.003922  0.000000  0.635294  0.007843  0.011765  0.701961   
1     0.647059  0.639216  0.698039  0.654902  0.654902  0.674510  0.654902   
2     0.003922  0.003922  0.000000  0.000000  0.003922  0.007843  0.003922   
3     0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
4     0.003922  0.000000  0.007843  0.007843  0.007843  0.007843  0.007843   
...        ...       ...       ...       ...       ...       ...       ...   
3251  0.000000  0.011765  0.000000  0.000000  0.000000  0.000000  0.000000   
3252  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
3253  0.019608  0.027451  0.101961  0.450980  0.031373  0.011765  0.003922   
3254  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
3255  0.035294  0.011765  0.015686  0.011765  0.003922  0.007843  0.003922   

        pixel8    pixel9   pixel10  ...  pixel50171  pixel50172  pixel50173  \
0     0.698039  0.737255  0.537255  ...    0.023529    0.011765    0.003922   
1     0.576471  0.588235  0.666667  ...    0.000000    0.000000    0.000000   
2     0.007843  0.007843  0.003922  ...    0.000000    0.000000    0.000000   
3     0.000000  0.000000  0.000000  ...    0.000000    0.003922    0.003922   
4     0.003922  0.000000  0.031373  ...    0.015686    0.019608    0.023529   
...        ...       ...       ...  ...         ...         ...         ...   
3251  0.003922  0.000000  0.000000  ...    0.000000    0.000000    0.000000   
3252  0.000000  0.000000  0.000000  ...    0.007843    0.003922    0.007843   
3253  0.007843  0.003922  0.023529  ...    0.000000    0.000000    0.003922   
3254  0.000000  0.000000  0.000000  ...    0.000000    0.000000    0.000000   
3255  0.003922  0.000000  0.003922  ...    0.000000    0.000000    0.000000   

      pixel50174  pixel50175  pixel50176  Benign  Early  Pre  Pro  
0       0.003922    0.011765    0.007843     1.0    0.0  0.0  0.0  
1       0.000000    0.000000    0.000000     0.0    1.0  0.0  0.0  
2       0.000000    0.000000    0.000000     0.0    1.0  0.0  0.0  
3       0.007843    0.011765    0.643137     1.0    0.0  0.0  0.0  
4       0.015686    0.003922    0.011765     0.0    0.0  0.0  1.0  
...          ...         ...         ...     ...    ...  ...  ...  
3251    0.000000    0.000000    0.000000     1.0    0.0  0.0  0.0  
3252    0.003922    0.019608    0.027451     0.0    0.0  1.0  0.0  
3253    0.003922    0.000000    0.003922     0.0    1.0  0.0  0.0  
3254    0.000000    0.000000    0.000000     0.0    0.0  1.0  0.0  
3255    0.000000    0.000000    0.000000     1.0    0.0  0.0  0.0  

[3256 rows x 50180 columns]

In [19]:
X = df.drop(columns=['Benign', 'Early', 'Pre', 'Pro']) 
y = df[['Benign', 'Early', 'Pre', 'Pro']] 

In [21]:
y = np.argmax(y.values, axis=1)

In [23]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [25]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [27]:
log_model = LogisticRegression(max_iter = 25000)
log_model.fit(X_train_scaled, y_train)

LogisticRegression(max_iter=25000)

In [29]:
y_pred = log_model.predict(X_test_scaled)


accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

print(f"Accuracy: {accuracy:.4f}")
print("\nConfusion Matrix:")
print(conf_matrix)
print("\nClassification Report:")
print(class_report)

Accuracy: 0.6580

Confusion Matrix:
[[ 32  30  32   7]
 [ 21 117  58   1]
 [ 14  49 122   8]
 [  2   0   1 158]]

Classification Report:
              precision    recall  f1-score   support

           0       0.46      0.32      0.38       101
           1       0.60      0.59      0.60       197
           2       0.57      0.63      0.60       193
           3       0.91      0.98      0.94       161

    accuracy                           0.66       652
   macro avg       0.64      0.63      0.63       652
weighted avg       0.65      0.66      0.65       652

